drop table PRODUCT_BRANDS;
CREATE TABLE [dbo].[PRODUCT_BRANDS] (
    [ID]            INT           IDENTITY (1, 1) NOT NULL,
    [BRAND_NAME]    NVARCHAR (50) NOT NULL,
    [BRAND_ORIGIN]  NVARCHAR (50) NULL,
    [IS_ACTIVE] BIT NULL DEFAULT 1, 
    [CREATE_USER]   NVARCHAR (10) NULL,
    [CREATE_DATE]   DATETIME      NULL,
    [CREATE_DEVICE] NVARCHAR (50) NULL,
    [UPDATE_USER]   NVARCHAR (10) NULL,
    [UPDATE_DATE]   DATETIME      NULL,
    [UPDATE_DEVICE] NVARCHAR (50) NULL,    
    PRIMARY KEY CLUSTERED ([ID] ASC),
    CONSTRAINT [UK_BRAND_NAME] UNIQUE NONCLUSTERED ([BRAND_NAME] ASC)
);

